Helpful hints for Positron on Workbench
posit-dev/positron-website pull request #18
Opened 2024-11-13 23:13 UTC by juliasilge

It is a very low lift for us to update this site (much easier than the Workbench docs themselves) so we can use this as a spot for flexibly adding advice to folks during the preview period.

What else do we want to include here?

2024-11-14 17:34 UTC, jthomasmock reviewed
Two additions, thanks Julia!

2024-11-14 17:34 UTC, jthomasmock commented on workbench.qmd
> +Posit Workbench runs on Linux, but CRAN doesn't build Linux binaries for R packages. You _can_ install R packages using the default configuration, but you will likely find the process extremely slow.
I would probably link directly to: https://packagemanager.posit.co/client/#/repos/cran/setup

2024-11-14 17:34 UTC, jthomasmock commented on workbench.qmd
> +title: "Positron on Workbench"
I also think it's worth calling out Python on the PATH and resource profiles. I'll add some language in this comment thread.

2024-11-14 17:34 UTC, jthomasmock commented on workbench.qmd
> +title: "Positron on Workbench"
```
### Resource Profiles

If your administrator has configured [Resource Profiles](https://docs.posit.co/ide/server-pro/getting_started/installation/kubernetes_installation.html#setup-resource-profiles) on Posit Workbench, you should allocate at least 4 GB of RAM when starting Positron sessions. 
We expect to make performance improvements in the future to decrease the memory needs of Positron. Follow along [on GitHub #5050](https://github.com/posit-dev/positron/issues/5050) to learn about our plans for a better solution in the long term.


### Python discovery

We plan to add admin configuration to set default and control runtime discovery, but in the meantime, we suggest adding [Python to the `PATH`](https://docs.posit.co/ide/server-pro/python/configuring_default.html) to ensure Positron can use it. 
Follow along [on GitHub #3574](https://github.com/posit-dev/positron/issues/3574) to learn about our plans for a better solution in the long term.
```

2024-11-19 04:36 UTC, AshleyHenry15 requested changes
You should probably hold this until the workbench release.

For docs - I have a "hold for release" label to indicate that the PR is being held on purpose.

2024-11-19 04:36 UTC, AshleyHenry15 commented on workbench.qmd
> +Positron is available as a preview feature on [Posit Workbench](https://posit.co/products/enterprise/workbench/) as of its 2024.12.0 release. Important information about using Positron on Posit Workb
```suggestion
Positron is available as a preview feature on [Posit Workbench](https://posit.co/products/enterprise/workbench/) as of its 2024.12.0 release. Important information about using Positron on Posit Workbench is available in the Workbench documentation [for administrators](https://docs.posit.co/ide/server-pro/2024.12.0/positron_sessions/) and [for users](https://docs.posit.co/ide/server-pro/user/2024.12.0/positron/getting-started/), but we also want to highlight a few ways to have the best possible experience during this preview period.
```

2024-11-19 04:36 UTC, AshleyHenry15 commented on workbench.qmd
> +Positron is available as a preview feature on [Posit Workbench](https://posit.co/products/enterprise/workbench/) as of its 2024.12.0 release. Important information about using Positron on Posit Workb
Also - Workbench hasn't released yet so we will likely want to hold this PR until its release.

2024-11-19 04:36 UTC, AshleyHenry15 commented on workbench.qmd
> +Posit Workbench runs on Linux, but CRAN doesn't build Linux binaries for R packages. You _can_ install R packages using the default configuration, but you will likely find the process extremely slow.
```suggestion
Posit Workbench runs on Linux, but CRAN doesn't build Linux binaries for R packages. You can install R packages using the default configuration, but it's likely that the process is extremely slow. Instead, consider using a CRAN-like repository that provides binaries for your Linux architecture, such as [Posit Package Manager](https://packagemanager.posit.co/client/#/repos/cran/setup) and set that via `options()` in R. For example, if Workbench is installed on Ubuntu 22.04 (Jammy), you would use:
```

2024-11-19 04:36 UTC, AshleyHenry15 commented on workbench.qmd
> +If you run this one time, you will set your `options` for the current R session. If you add this code to the `.Rprofile` in your home directory on Workbench, it will apply to all your R sessions.
I don't want to butcher the PR because I haven't given the rest of the guide a review but this is future tense. We strive to write the product doc in active voice as much as possible (it is a disaster and a WIP). So, I will just comment here vs. suggesting a rewrite here.

2024-11-19 04:36 UTC, AshleyHenry15 commented on workbench.qmd
> +We expect to make performance improvements in the future to decrease the memory needs of Positron. Follow along [on GitHub](https://github.com/posit-dev/positron/issues/5050) to learn about our plans
https://positpbc.atlassian.net/wiki/spaces/ENG/pages/594509972/Posit+Documentation+Style+Guide#Links[inlineExtension]

2024-11-19 04:36 UTC, AshleyHenry15 commented on workbench.qmd
> +:::{.callout-note}
Voiceover doesn't seem to recognize inline links tied to headings/files. We tested it earlier. I would change this:
 [directly to the Positron team](/feedback.qmd)
 to 
Use the Feedback and Users to provide feedback directly to the Positron team.

2024-11-19 14:50 UTC, AshleyHenry15 commented
@jthomasmock @juliasilge 

I think that some of this isn't appropriate for the Positron docs. 

Having Workbench docs in the Positron guide seems to suggest that we are showing a lot of favoritism and pushing/promoting Workbench. It also becomes another place that we have to track and update. 

>It is a very low lift for us to update this site (much easier than the Workbench docs themselves) so we can use this as a spot for flexibly adding advice to folks during the preview period.

The Workbench docs follow the same updating process as Positron—they can be rolled out whenever, and you can build them locally using `quarto preview`.

Anything Workbench-related should stay in the Workbench docs. 
I don't think it hurts to note some of these things but maybe we just link to the Workbench docs vs. covering things like resource profiles and R discovery in the Positron guide.

By introducing this content here, we now have 3+ places (like 10+ with support articles) where we cover resource profiles and R discovery, and I think adding another place is further degrading our user experience.

2024-11-19 14:59 UTC, AshleyHenry15 commented
@juliasilge - I can help with/facilitate WB doc updates if it helps alleviate some of the burden. Not a problem - happy to help!

2024-11-19 16:56 UTC, juliasilge commented
I'm happy for this to go into the Workbench docs if the consensus is that it's a better option! What I think is important that we have in the *user* docs in that case includes:

- very explicit info on how to set up binary R packages, need for Python on the `PATH`, resource profiles
- links to the GH issues for the big difficulties, so folks can follow along with improvements
- a link to our [feedback](https://positron.posit.co/feedback) page surfaced fairly prominently

2024-12-10 19:54 UTC, sharon-wang commented
I'll port this content over to the Workbench User Guide.

2024-12-12 21:17 UTC, sharon-wang commented on workbench.qmd
> +Positron is available as a preview feature on [Posit Workbench](https://posit.co/products/enterprise/workbench/) as of its 2024.12.0 release. Important information about using Positron on Posit Workb
@juliasilge The hints have been moved over to the Workbench User Guide and are available at: https://docs.posit.co/ide/server-pro/user/2024.12.0/positron/getting-started/!

Now that the main content is in the Workbench docs, maybe we just need this blurb? We could link directly to https://docs.posit.co/ide/server-pro/user/2024.12.0/positron/reference/other-resources.html in addition to the User Guide and Admin Guide links already in this blurb.

2024-12-13 23:59 UTC, juliasilge commented
Thank you so much @sharon-wang! We'll close this PR and after the Workbench release add a link to the user docs somewhere, maybe at the bottom of <https://positron.posit.co/start>? I don't think we need a whole page anymore.

Thanks, all! 🙌

2024-12-13 23:59 UTC, closed without merging